runmode: debug                 # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: pickup              # API Server的名字
url: 127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
db:  # DB 配置 部署时环境变量覆盖
  name: PICKUP
  addr: 127.0.0.1:3306
  username: 
  password: 
